---
preset: "extended"
resume: true
scheme: SEMVER
dryRun: false
initialVersion: "0.0.0"
releaseLenient: true
releasePrefix: v
summary: true
summaryFile: "build/.nyx-summary.txt"
stateFile: "build/.nyx-state.yml"
changelog:
  append: "head"
  path: "build/CHANGELOG.md"
  sections:
    "Added": "^feat$"
    "Fixed": "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://example.com/issues/%s)"
commitMessageConventions:
  enabled:
    - conventionalCommits
  items:
    conventionalCommits:
      expression: "(?m)^(?<type>[a-zA-Z0-9_]+)(\\((?<scope>[\u4e00-\u9fa5a-zA-Z ]+)\\))?(!)?:( (?<title>.+))$(?s).*"
      bumpExpressions:
        major: "(?s)(?m)^[a-zA-Z0-9_]+(\\([\u4e00-\u9fa5a-zA-Z ]+\\))?(!: .*|.*^(BREAKING( |-)CHANGE: )).*"
        minor: "(?s)(?m)^feat(!{0})(\\([\u4e00-\u9fa5a-zA-Z ]+\\))?: (?!.*^(BREAKING( |-)CHANGE: )).*"
        patch: "(?s)(?m)^fix(!{0})(\\([\u4e00-\u9fa5a-zA-Z ]+\\))?: (?!.*^(BREAKING( |-)CHANGE: )).*"
git:
  remotes:
    origin:
      authenticationMethod: USER_PASSWORD
      user: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      password: ""
services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "learn-github"
      REPOSITORY_OWNER: "louruixiao"
releaseTypes:
  enabled:
    - mainline
    - integration
    - feature
    - hotfix
    - internal
  publicationServices:
    - github
  remoteRepositories:
    - origin
  items:
    mainline:
      collapseVersions: false
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitCommit: "false"
      gitPush: "true"
      gitPushForce: "true"
      gitTag: "true"
      gitTagForce: "true"
      gitTagMessage: "Tag version "
      gitTagNames:
        - "latest"
      matchBranches: ^(master|main)$
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      releaseName: "Release "
      versionRangeFromBranchName: false
    integration:
      collapseVersions: true
      collapsedVersionQualifier: "alpha"
      description: "Integration release "
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(dev|develop|development|integration|latest)(\\.([0-9]\\d*))?)$"
      gitCommit: "false"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(dev|develop|development|integration|latest)$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"
      releaseName: "Pre Release "
      versionRangeFromBranchName: false
    feature:
      collapseVersions: true
      collapsedVersionQualifier: ""
      description: "Feature release "
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(feat|feature)(([0-9a-zA-Z]*)(\\.([0-9]\\d*))?)?)$"
      gitCommit: "false"
      gitPush: "false"
      gitTag: "false"
      matchBranches: "^(feat|feature)((-|\\/)[0-9a-zA-Z-_]+)?$"
      publish: "false"
      versionRangeFromBranchName: false
    hotfix:
      collapseVersions: true
      collapsedVersionQualifier: ""
      description: "Hotfix release "
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(fix|hotfix)(([0-9a-zA-Z]*)(\\.([0-9]\\d*))?)?)$"
      gitCommit: "false"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(fix|hotfix)((-|\\/)[0-9a-zA-Z-_]+)?$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"
      versionRangeFromBranchName: false
    internal:
      collapseVersions: true
      collapsedVersionQualifier: "internal"
      description: "Internal release "
      gitCommit: "false"
      gitPush: "false"
      gitTag: "false"
      identifiers:
        -
          position: BUILD
          qualifier: "{{environmentUser}}"
          value: ""
        -
          position: BUILD
          qualifier: "{{branch}}"
          value: ""
        -
          position: BUILD
          qualifier: '{{#timeFormat format="yyyy-MM-dd"}}{{/timeFormat}}'
          value: ""
      publish: "false"
      versionRangeFromBranchName: false
