name: 发布
on:
  push:
    branches:
      - main
jobs:
  build-project:
    name: 构建项目
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 输出
        run: |
          echo "GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }}"
          git remote -v
          git config --global user.name 'louruixiao'
          git config --global user.email '775674502@qq.com'
          git remote set-url origin https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
      - name: 发行版本
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote -v
          ./gradlew nyxPublish --stacktrace